services:
  db:
    image: postgres:12.11
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: eshop_brasil_tracker_development

volumes:
  db-data:
